name: iOS Build and Deploy to TestFlight

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to TestFlight
    runs-on: macos-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Build iOS app
    - name: Build iOS Release
      run: flutter build ios --release

    # Install Fastlane
    - name: Install Fastlane
      run: sudo gem install fastlane

    # Deploy to TestFlight
    - name: Deploy to TestFlight
      run: |
        cd ios
        fastlane init
        fastlane pilot upload --ipa ../build/ios/ipa/Runner.ipa
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        TEAM_ID: ${{ secrets.TEAM_ID }}
        ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
